### ISSUE TITLE
Dino, Tex, Rex fail to render correctly. Layout issues preventing visibility

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#138]
Dino, Tex, Rex are all incorrectly cropping the main area in 2.8 when run under k8s.
Glossary/Server author seem ok
This issue occurs in chrome & firefox

Examples follow:
<img width="1611" alt="Screenshot 2021-04-02 at 12 43 48" src="https://user-images.githubusercontent.com/7292002/113412884-4f11e780-93b1-11eb-8ef7-54f579e12f66.png">
<img width="1612" alt="Screenshot 2021-04-02 at 12 43 56" src="https://user-images.githubusercontent.com/7292002/113412890-50dbab00-93b1-11eb-917d-e08d37593c10.png">
<img width="1608" alt="Screenshot 2021-04-02 at 12 44 05" src="https://user-images.githubusercontent.com/7292002/113412892-51744180-93b1-11eb-9667-462e42e96c29.png">

**Comment by davidradl** [comment]
Hi @planetf1 is this a regression? Or has this always been like this. I am trying to assess its priority.

**Comment by planetf1** [comment]
regression it seems. on call now but looking at this am. Was going to check prior version

**Comment by davidradl** [comment]
I assume this is nothing to do with running it under Kubernetes. 
I am running the current code (dev mode if that makes any difference) and I do not see any layout issues. Seems ok in full screen and as a sized window.
Does your screen resolution make any difference?

**Comment by davidradl** [comment]
I would be worth clearing your cache in case this is causing it.

**Comment by planetf1** [comment]
It's not browser/cache specific - occurred when I tried in firefox, chrome, safari.
It could be k8s/container specific -- I built locally and did not see the issue. Could be the build process, or the runtime container. Trying to distinguish this now. However the end result is unusable, which wasn't the case in the previous release.

**Comment by planetf1** [comment]
It is not specific to the container environment. I've just pulled the build from the last release-2.8 merge at https://github.com/odpi/egeria-react-ui/actions/runs/698958245 (there's a badly named attachment - against which I run 'npm run prod' in 'cra-server') and this shows the same layout issue.

Running the latest master from https://github.com/odpi/egeria-react-ui/actions/runs/709009604 -- same layout issue

I tried the 'release-2.7' branch and it works fine, so this is certainly a regression in the 2.8 timeline. If we can't resolve promptly (I'll look some more) I propose to add an entry to the egeria release notes recommending use of 2.7 & updating the references in the charts etc to continue using 2.7 for the UI as dino/rex/tex are the most useful components currently.

**Comment by planetf1** [comment]
Ok,
 I've tried a rebuild (npm run install) after REMOVING the package-lock.json file. The UI now works.
 
 As originally reported in #77 I was concerned this approach could cause issues down the line with the ci/cd process, and it seems to have.
 
  Presumably @davidradl your environment works as you have a good set of dependencies present, but we need to ensure the authoritative copy is that in the build environment, and based on specific versions we recommend/provide in containers etc - or we allow for local resolution without them. I'm still not quite sure of the best way to do this but we need to investigate BEFORE the next release
  
   My tactical suggestion for 2.8 is to remove the lock files. I will create a PR for that now on the empirical basis that it works. I'm reluctant to update them as all that may happen is my resolution will break your environment, or others.

**Comment by planetf1** [comment]
If we decide the lock files need to be checked in, we may need to do this as part of the 'official' npm build process rather than making it a developer task, so that we have a strictly controlled environment

**Comment by planetf1** [comment]
Current build infra versions are:
```
v14.16.0
6.14.11
```

**Comment by planetf1** [comment]
Been looking at changes, npm/node versions, but still consistently get build failing to work correctly with 2.8
Very likely now to flip back our charts etc to the previous version and add note to readme

**Comment by davidradl** [comment]
Thank for look at this Nigel. Can I confirm, does it work if
- you remove the package lock files
- use the same levels of npm and node as 2.7?
- with the above 2 things in place what other regressions are you seeing over 2.7?

**Comment by planetf1** [comment]
I tried a selection of the above. Egeria 2.8 has now shipped with the charts etc pointing to the 2.7 ui. Let's review when you are back.

**Comment by davidradl** [comment]
@planetf1 ok sounds good. I cannot recreate. It works in production mode and development mode locally for me on the latest code; following the readme instructions to build. Any suggestions on how I can recreate?

**Comment by planetf1** [comment]
What happens if you build on a clean machine? What about Linux? Do you see the error if you run the docker container? Or the helm lab chart or docker compose?
What versions of node/npm are you using?
Can talk through this when you're back

**Comment by planetf1** [comment]
Have you checked with the release-2.8 branch in case you fixed it since we branched?

**Comment by davidradl** [comment]
I have not changed that area - but I guess it is possible; it might be my local npm & node is lucky.I will give it a go.

**Comment by planetf1** [comment]
Until this is addressed we cannot update the UI as used by our packaged environments. A 2.9 release will be branched in around a week, so we could really do with getting to the bottom of this by then.

Without this change, none of the other improvements in the UI will be seen by those using the charts for example.

I'll build again myself to check now...
