### ISSUE TITLE
Glossary Author display css improvements

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#143]
A change to the Carbon UI shell, meant we needed to amend the css for Tex Rex and Dino. I had not noticed that full screen Glossary Author was also effected - as I had only tested with the chrome debugger on which took up horizontal real estate, si I did not see the issue; the Rex Tex and Dino issue involved vertical real estate. 

@planetf1 hoping to get this into release 2.9 and make the minor CSS changes Mandy asked for in this pr as well.

**Comment by planetf1** [comment]
ok sounds good - I was planning to branch sun, but I'm less concerned on the UI in leaving it a few more days if needed as the impact is limited.
