### ISSUE TITLE
release 2.10

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#167]

**Comment by planetf1** [comment]
Note that I've replaced the text in the README for release notes with a note to review the github history. Having wordy text
referring to dev vs master is additional overhead for managing each release. Easiest to just keep it to incrementing version numbers until the release notes become separated out with specific content for the UI release

**Comment by davidradl** [comment]
can we close this @planetf1

**Comment by planetf1** [comment]
yes!
