### ISSUE TITLE
Glossary author OMVS should be solution view or integration view

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#173]
Using coco k8s environment testing 2.10

Dino throws the error:
```
View service Glossary Author OMVS should be configured as either a SolutionViewService or an IntegrationViewService
```
When navigating into cocoView1 -> View Services configuration

<img width="1356" alt="Screenshot 2021-05-28 at 11 11 14" src="https://user-images.githubusercontent.com/7292002/119968690-a8f3ef80-bfa5-11eb-934f-07403624e4d7.png">

**Comment by planetf1** [comment]
Also occurs when clicking Server Stats/Audit Log -> Get Server Audit Log -- after getting the above error

**Comment by davidradl** [comment]
I can't find that message you see in the alert in the code in either repository! The closest I found is ```
VIEW_SERVICE_CONFIG(400, "OMAG-ADMIN-400-042",
                          "The {0} Open Metadata View Service (OMVS) has been passed an invalid configuration of {1} in the {2} property.",
                          "The view service has not been passed valid configuration.",
                          "Check whether the view service expects SolutionViewServiceConfiguration or IntegrationViewServiceConfiguration, correct the configuration and restart the server.
```"),
". But is not the same text as your popup. Also Dino does 2 alerts neither of them match what you see. Could this be out of date code; before Graham standardised the error processing.

When I get time I will attempt to recreate.

**Comment by mandy-chessell** [comment]
The message is coming from `egeria-react-ui/cra-client/src/components/Dino/components/details-panel/ServerConfigServicesDisplay.js`

**Comment by mandy-chessell** [comment]
This is the code:
```
const getServiceName = (service) => {
    let serviceName = null;
    switch (service.class) {
      /*
       * View Services
       */
      case "IntegrationViewServiceConfig":
        serviceName = service.viewServiceFullName;
        break;
      case "SolutionViewServiceConfig":
        serviceName = service.viewServiceFullName;
        break;
      case "ViewServiceConfig":
        alert("View service "+service.viewServiceFullName+" should be configured as either a SolutionViewService or an IntegrationViewService");
        serviceName = service.viewServiceFullName;
        break;
      /*
       * Access Services
       */
      case "AccessServiceConfig":
        serviceName = service.accessServiceFullName;
        break;
      
      default:
        console.log("getServiceName: does not yet support this type of service!");
        break;
    }
    return serviceName;
  }
```

**Comment by davidradl** [comment]
@mandy-chessell  @planetf1 Thanks for the updates. I will have a look

**Comment by davidradl** [comment]
@planetf1 @mandy-chessell 

I have had a look at this. Graham had originally set up 2 child classes of ViewServiceConfig,
one for solutions and one for integration services. The original integration services added extra content, which is the resources and endpoints. The Solution service configs did not add extra content. I did not use this child class for Glossary Author - as there was no real need. 

We either 
1- allow glossary author to be defined with SolutionViewServiceConfig. If we do this we should not allow it to be defined 
with IntegrationViewServiceConfig or ViewServiceConfig server side and in Dino. The advantage of this is that we could use the class to determine whether the config is an Integration or a solution view service explicitly. The downside is that there is extra complexity for little / no gain.  
or 
2-we remove the SolutionViewServiceConfig class, from the server and documentation and remove this checking from Dino. We could add in other child classes as the need arises. We can still use the class to identify the config as Integration or not. If it is not, then it would be a solution view config. 

I am thinking 2) but wanted to know your thoughts.

**Comment by davidradl** [comment]
@planetf1 @mandy-chessell I will proceed with 2) .

**Comment by planetf1** [comment]
Retested - issue has been fixed

**Comment by planetf1** [comment]
Reopening, as this issue has reoccurred using 3.8.0-rc.0
It's possible it's intermittent:
<img width="1249" alt="Screenshot 2022-04-26 at 12 09 41" src="https://user-images.githubusercontent.com/7292002/165287395-9cef6502-c680-4935-baa0-f6768a1a3d8b.png">

This occurs when selecting the view server ('view1' on coco) and trying to expand 'server configuration'

**Comment by planetf1** [comment]
when the message is closed, one can continue to view the config
