### ISSUE TITLE
Configure a server author view service in the UI  and early bootstrapping

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#237]
The nodejs we server is defined to point to a platform.
When the server author option is chosen in the react UI:
1) We need to issue an admin call to see what servers are defined on the platform.
2) If there is nothing defined, then we ask the user to name the platform they are connected to.
3) We now author a view server with a server author view service using admin calls.
4) As part of this authoring,  the view server needs an audit destination to be defined
5)The Ui code needs to start the view server so it can issue the server author calls to the server author view API.
6) Subsequent authoring of the other server types will be done using the server author view API 

@mandy-chessell @planetf1 @cmgrote @lpalashevski any feedback?

**Comment by planetf1** [comment]
This sounds good to me in the initial case of a clean environment to help someone get going having done no more than launch the platform - it will make that first step so much easier. That environment could be for development, production, or just (for example) authoring for k8s deployment (elsewhere)

A few edge cases:
 * An enterprise deployment is setup with no (view?) servers. For example through k8s which will only start a few platforms. If a security plugin is in place at the platform level the option to create a server may be blocked. If an end user started the UI the create would then fail. It's a pretty unrealistic case! And I think just ensuring a good clear error message is the right way to handle (should tell them either to do manual equivilents, possibly through a doc link, or consult admin deployer etc)
  * When you say you check if servers are defined - do you mean any server? (and would then fail with error as above, on basis admin is already setting things up) Or just referring to view servers?
 * What if view server exist, but are not started ? Do we start it?
 * How should we name the view server? Fixed name? Uniquely generated name 
 * Should we configure this new view server to auto-start?
