### ISSUE TITLE
Improve error paths during login experience

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#257]
I have defined the below 2 servers. 
In the ccc case  simpleview does not exist on the server - so should fail the login. It does not fail the login. 
In the ddd case - it fails because the platform pointed to by the environment variable is not available, but the popup is not very helpful.

EGERIA_PRESENTATIONSERVER_SERVER_ccc={"remoteServerName":"simpleview","remoteURL":"https://localhost:9443"}
EGERIA_PRESENTATIONSERVER_SERVER_ddd={"remoteServerName":"simpleview2","remoteURL":"https://localhost:9444"}

**Comment by planetf1** [comment]
These are also related (and may be fixed by this)
 #41 (backend issues)
 #139 (login URL)
 #90 (terminology)
