### ISSUE TITLE
(Release 3.2) Dino can no longer display server config document

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#264]
* Run the coco/lab environment
* configure/start servers
* Navigate to react UI URL (/coco)
* Login as garygeeke
* Go to Dino
* Click on any server
* Expand 'Server Configuration'

Briefly see 'Loading' followed by a blank screen
The logs from stdout/err on the presentation server don't indicate any errors, and do in fact dump out the server config document

**Comment by planetf1** [comment]
@davidradl @mandy-chessell I cannot get this to work. 
Do we need to fix for release? Or add to release note?
Does it work for you david?

**Comment by planetf1** [comment]
Since the API appears to work, this looks predominantly like a UI issue. I will add an entry to the README pointing to this issue.

**Comment by davidradl** [comment]
@planetf1 I am investigating now. If I fix it in the next couple of hours - can it get into the release?

**Comment by planetf1** [comment]
The referenced commit has been added to 3.2
However the code fix does not fix the reported issue - I am still unable to load a config document in 3.2
I will add an entry to the release notes & link here.

**Comment by davidradl** [comment]
Interesting. @planetf1. It could view the one I was failing on. For me, it was attempting to check for Kafka producers and consumers from an undefined javascript object. Please could you send me a copy of the config you are attempting to view? I assume there is another bug that your config is exposing.

**Comment by planetf1** [comment]
I don't have it right now, but it was the standard coco lab config. If you run the configuring/starting the coco servers, and then use you'll see the failure.

You can also find the configs for the coco environment in the k8s operator repo (as they're used for validation/initial loading) at https://github.com/odpi/egeria-k8s-operator/tree/master/samples/server

**Comment by planetf1** [comment]
This is still failing in 3.3
Proposal - will leave in release notes

**Comment by davidradl** [comment]
@planetf1 ok to close this ?
