### ISSUE TITLE
Suggestion: Type Explorer should display cardinality on relationships

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#293]
* Lookup a type in Type Explorer, for example 'Form' 
* Review list of relationships
* Expand out definitions of relationships
* Observed that there is no display of the cardinality of that relationship

This would be a useful feature to have in the UI for exploring types

**Comment by planetf1** [comment]
Additionally - to aid in navigation debug, TEX could display (and allow search?) of type gid?

**Comment by davidradl** [comment]
@planetf1  On the cardinality - if you click on more details the cardinality is shown for each end of the RelationshipDef. I am not sure what the use case would be for starting with the TypeDef guid and not knowing the name, the name of the typedef is unique and human readable and seems the natural place to start. What debug situation are you thinking of where the typedef guid would help and we do not have the name - I suspect @grahamwallis purposely hid the typedef guid in tex from the user - so it would be a more natural experience.

**Comment by planetf1** [comment]
* cardinality - thanks for clarification

* guid - a) where the guid is reported in audit log events without name b) when reviewing code [to check definition in repo looks as expected] . I don't have explicit examples currently, so ok if you close, and if I come across a specific scenario where it would help I can document & reopen.
