### ISSUE TITLE
Update certs - now expired

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#376]
See https://github.com/odpi/egeria/issues/6326

the UI needs to be updated with the latest certificate(s) which expired yesterday

This is a short-term fix. Also in odpi/egeria#6326 we need to figure out a better long term approach.

**Comment by planetf1** [comment]
@davidradl this should really be done for the 3.7 release of the UI
Certs can be retrieved from base egeria

**Comment by davidradl** [comment]
@planetf1 can I check that the Egeria cor ode is released at 3.7 so I can proceed with the react ui ?

**Comment by planetf1** [comment]
Clarifications:

In that directory open-metadata-resources/open-metadata-deployment/certificates there are a variety of files/formats.
The idea was that you have different certificates the the two roles
React UI server (presumably this is what connects to the view server, with will use the EgeriaServerChassis cert)
React UI client (which is presumably what the browser connects to)
Then in addition the truststore should contain the certification authority we use. The script currently uses the EgeriaRootCA
In each of these directory/base file names we tend to have both a .p12 file (which is like an archive) as well as individual certificates which end in ‘.pem’ - in fact there’s usually several files
cert.pem - the actual certificate
csr.pem - certificate signing request - this is an intermediate file that we wouldn’t use
key.pem - the actual key
So when you say you need a crt or cert, I suspect it is the file ending cert.pem, and for the truststore use EgeriaRootCA/(whatever file you want).
Not sure how you sort out the two roles in your code for client/server — I think we had opened up an issue on the UI to do this properly, but never revisited it.
Note that the whole area of how to distribute our certs is still a ‘todo’'

**Comment by planetf1** [comment]
The UI is now functioning correctly.
In the helm chart cert validation is disabled
The long term fix is to correct the certs used in the charts
