### ISSUE TITLE
Dino - Error retrieving cohort information

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#463]
Egeria 3.9, react-ui 3.8.0, coco pharma k8s environment

Navigate to cocoMDS1 -> Server Configuration -> Repository Services Configuration -> Configured Cohorts -> cocoCohort
Error 'Cannot add cohort for unknown server cocoMDS1'

The cohort information is shown in the details pane. The error seems to be caused by the cohort being added to the visual graph before this section is expanded - and it then tries to add again?

**Comment by davidradl** [comment]
I also notice that for repository proxies there is an empty cohorts top section. The cohort display should be consistent between metadata servers and repository proxies

**Comment by planetf1** [comment]
still occurs in v4
