### ISSUE TITLE
Presentation Server: SSL configuration

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#51]
In odpi/egeria#3389 we are removing the default behaviour to skip SSL validation within the core egeria code (server, clients, samples)
Once this is merged...

The Presentation Server code currently also skips ssl verification

This should
 * default to performing full ssl verification
 * Provide configuration to disable verification if needed
 * Ensure the relevant docs for deployment explain how to do this, as well as configure TLS similar to https://egeria-project.org/open-metadata-implementation/admin-services/docs/user/omag-server-platform-transport-level-security.html
 * Ensure any samples (like the egeria tutorial environment) appropriately configures a certificate or skips the check

Note: will likely need to transfer to the egeria-presentation-server repo once code migrates

**Comment by davidradl** [comment]
https://github.com/odpi/egeria-react-ui/pull/87 removes the hard coded security artefacts from the code. Then we need improved p12 certificates and other security artefacts so we can use those rather than the current ones.
