### ISSUE TITLE
Server author UI - not usable in 2.6 & breaks logged in user context for rex/tex/dino etc

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#60]
In the coco pharma lab environment, the server author UI is not reporting all servers. For example I only see:

<img width="1265" alt="Screenshot 2021-01-28 at 13 23 49" src="https://user-images.githubusercontent.com/7292002/106144428-13b62b00-616c-11eb-912e-d011b44545d6.png">

This was seen in testing 2.6 .. however server author UI is still very much in dev, so just adding this
for future work

In addition the UI shows a list of servers and one can be selected to shutdown. However there is no confirmation this has been actioned, since we do not show the status of the server. The shutdown and delete does work properly at the backend and the server is deleted. 
Start does not seem to work
Create new server gives:

<img width="1260" alt="Screenshot 2021-01-28 at 13 27 52" src="https://user-images.githubusercontent.com/7292002/106144822-a5259d00-616c-11eb-8fcf-d8ea14801044.png">

Note the user pollytasker - not being picked up from logged in user context - in fact EVEN WORSE - navigating to this ui then CHANGES the logged in user, so returning to Dino/tex/rex then fails!

One challenge for the user is seeing a menu item on the UI which is not ready to use.

At a minimum I think we need to make it clear (in text/graphic) that the UI is not working/under construction ... and maybe have a prod build that excludes it.

**Comment by planetf1** [comment]
cc: @sarbull

**Comment by davidradl** [comment]
Hi Nigel,
I am not sure what you mean by "the user pollytasker - not being picked up from logged in user context ". Are you saying you login with a user that is not pollytasker? It looks like pollytasker is not authorised to perform the admin calls, does this work with garygeeke, who I think has got authority. I am wondering whether the issues you are seeing only occur after the authorisation failure. This was working last week in non-error paths, i.e. no evidence of users being switched out?
I see no hard coding of pollytasker in the server author code.

I suggest "However there is no confirmation this has been actioned, since we do not show the status of the server." be raised as a separate issue. 
@planetf1

**Comment by planetf1** [comment]
@davidradl No, I only login as garygeeke. I never logged in as pollytasker but got switched to this when clicking back in to this UI from rex/tex.

There's a few issues all in this area -- which could be split out, but may just be work in progress -- ie the status, feedback on action, the list of servers is incomplete. Probably easiest of the component owner figures how you want to track given it's an area under progress.

My biggest concern is the potential confusion for anyone using the UI in not knowing these areas are work in progress, since I know more people are now using them for rex/tex/dino, and then start exploring other areas. I can add something to the release notes for 2.6, but really I think we need to cut down the UI or make it obvious those pieces are very much in development?

**Comment by davidradl** [comment]
@planetf1 I have used the latest code on Egeria and Egeria react ui, I ran the notebooks locally, specifically I ran the building a catalog notebook. 
 I the. logged in to the Egeria React UI with garygeeke (I had the ,env file pointing to the platform with port 9444). I ran Rex  the switched to server author , then switch ed to tex , then back to server author. I did not see the polytasker error you mention. Please could you detail the steps I need to perform to reproduce the main issue you are seeing. 

Looking at the server author, the main functionality that has been produced is to producer a new server config and start it. 
I see there is a list of known servers with status is known; it seems that started or stopped would have been more relevant and then only allow start or shutdown appropriately. Also it seems this is very much Dino territory. What do you think @grahamwallis ?

**Comment by davidradl** [comment]
@planetf1 I notice that the docs talk of configuring `EGERIA_PRESENTATIONSERVER_SERVER_aaa={"remoteServerName":"cocoView1","remoteURL":"https://localhost:9443`. This is not correct, cocoView1 lives on the data lake platform which has port 9444.

**Comment by planetf1** [comment]
> @planetf1 I notice that the docs talk of configuring `EGERIA_PRESENTATIONSERVER_SERVER_aaa={"remoteServerName":"cocoView1","remoteURL":"https://localhost:9443`. This is not correct, cocoView1 lives on the data lake platform which has port 9444. I was thinking that for the lab, it would be better to use 'coco' or 'cocopharmaceuticals' rather than 'aaa'.

It's going to depend on the context of the docs. If it is merely referring to an example of how to set the configuration, I think this text is consistent with docs we have elsewhere, in that we usually refer to localhost:9443

If this doc is in the context of the coco scenario, then I agree it should refer to datalake

In this case, the use of _aaa implies it isn't coco, and the docs appear in the README, so I don't think it's wrong. However more elaboration on what the configuration means could be useful?

(will retest the scenario today)

**Comment by planetf1** [comment]
On server author - good point about dino. To some extent it would be better to keep server operation in dino - but then one can question whether server author is a different role? It is slightly, but in practical terms would it be the same user? And if so should server author be within dino? If seperate, perhaps both start and stop need to be removed and purely allow server author to create the config document. To have start but no stop seems odd (asymmetric...) But also if it is a unique UI, the server author should be able to browse and modify the stored config (within whatever limits we define)

**Comment by planetf1** [comment]
I'm proposing to add a note to the readme for 2.6 to point out that glossary author and server author are currently in development with known issues and limitations
