### ISSUE TITLE
Repository Explorer - blank window when clicking on node in visual graph

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#631]
* Install odpi-egeria-lab helm chart (--prerelease .. for version 4)
* Run configuration notebook
* Run 'building a data catalog'
* Open up react ui & login as garygeeke
* Launch REX
* Click on cocoMDS2 and search for .*
* Select All items found & add to graph
* Click on one of the graphical nodes on the graph

At this point the web page loads a blank screen.

This occurs in safari 16.4

Not yet tested standalone.

Critical issue to address for Egeria release 4.0

cc: @dwolfson

**Comment by planetf1** [comment]
Also tested
 - Locally (macOS) (multiple platforms & node server)
 - Chrome
 
 Same behaviour noted

**Comment by planetf1** [comment]
TEX seems ok

**Comment by planetf1** [comment]
No odd messages noticed in
 - output from node server
 - platform running view servers

**Comment by planetf1** [comment]
@davidradl Do you have any thoughts on what might cause this? 
The code itself hasn't changed

**Comment by davidradl** [comment]
@planetf1 are you using the latest code - as I merged in the check for undefined yesterday, which gave this symptom.
You could put on the developer tools on chrome and see if there is more diagnostics there - there usually is.

**Comment by planetf1** [comment]
Thanks. I'll check again.

**Comment by planetf1** [comment]
I have tested locally. The UI seems to work normally :-)

I see there is a new prerelease container, so I will try that also

**Comment by planetf1** [comment]
Tested in containers - also all good, so closing.
