### ISSUE TITLE
UI should hide areas under development by default

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#68]
The egeria react UI is exceptionally useful in some areas and no doubt will be quickly adopted by many.
These areas include tex, rex, dino

We want to point users at these UIs, blog about them, referring to them in docs etc.

We ALSO have other UI areas that are very much in development - for example Server Author & glossary. A user may click on these and wonder if they are meant to work, or get confused when they don't. (I've already had slack messages on this).

I propose we consider 'guarding' areas under development behind some kind of feature flag - be it build time (less nice), runtime (ie env var/property - a good balance?), or user preference 'Advanced->There be Dragons'

**Comment by grahamwallis** [comment]
Good idea - one very simple way of doing it would be to split the navigation pane so that the UI components that are still under development appear below a separator...e.g:
```
Type Explorer
Repository Explorer
...
-----------------------
"In development" or "Coming soon"
Server Author
...
```

**Comment by planetf1** [comment]
This is particularly acute with server author which seems confusing and is not suitable for general use (yet)

**Comment by planetf1** [comment]
These areas have developed more. Going to close this as the design develops but will need to take care with docs/advice
