### ISSUE TITLE
Amend Axios calls to not use rejectUnauthorized

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#73]
Pull request https://github.com/odpi/egeria-react-ui/pull/72 dismissed 2 CodeQL complaining about the use of rejectUnauthorized: false.

This

**Comment by davidradl** [comment]
note the browser to node js ssl side of this in being addressed separatelhy in https://github.com/odpi/egeria-react-ui/issues/74

**Comment by davidradl** [comment]
@planetf1 The passphrase is hard coded currently- I think we need to change this to an environment variable , this will have an impact on other users and we might want to expose the p12 files location as environment variables as well. I suggest we handle this in a separate issue.

**Comment by planetf1** [comment]
I believe what 'rejectUnauthorized: false.' says is to ignore checking of certificates. 

I take it this is in your CLIENT code where you connect to the backend egeria services?
If so there should be no need to have this statement - correct configuration even of the egeria 'self-signed' certs should allow it to work fine.
So this is the right change, but needn't in itself require other changes.

Passphrases should be a secret - agreed
In cases where you need to select which cert to use, and you store that in a p12 file, you may also need an identifier to select which cert to use.
