### ISSUE TITLE
Review what ssl orientated parameters should be obtained from the environment variables.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#76]
Passphrase and the location of the p12 files are candidates

**Comment by planetf1** [comment]
For anything credential related, if I were deploying in a Kubernetes environments I'd most likely expect these to be stored in Secrets

Secrets can be easily exposed as (https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/)
 - files, or more specifically a 'volume'. ie think of this as a directory containing files created prior to deployment (or updated after). We effectively have key (filename) and value (file contents)
  - environment variables. Basically just a set of key-value pairs
  
  So either work fine...

**Comment by planetf1** [comment]
In plain docker again, though there's no explicit 'secrets' there are volumes and env vars. How they are managed is up to the user.. But it doesn't really change the approach. IMO env vars are more flexible

**Comment by planetf1** [comment]
From https://nodejs.org/api/https.html#https_https_request_options_callback it looks like agents generally accept: ca, cert, ciphers, clientCertEngine, key, passphrase, pfx, rejectUnauthorized, secureProtocol, servername

These seem to be better documented at:
  https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

In theory any of these parms might want to be configurable.. but currently I think it would be ok to assume defaults. In base egeria I did start writing explicit code for this (which could support tenants) but ended up defaulting to standard jvm defaults and overrides (-D xxxx). .

It may be worth looking at what other node based apps tend to offer in terms of configuration.

But for now I suggest:
Reviewing the code in route.js

ca parm
--
 * When we use the truststore.p12 we pass it (decoded from file) currently to httpAgent as the 'Certification Authority' using the 'ca' parm.  
 * Whilst the api does allow the use of a separate cert and key, it is easy to convert between the two formats, and .p12 is very standard, so just supporting this seems to be fine. I think it should be optional, though for our 'out of the box' / 'demo' environment we will want to use it as we have our local Egeria CA. In production use this won't be the case. Some orgs may have their own private ones, most will likely have a chain that is supported by the mozilla defaults
 * I would probably document this parameter as 'Optional PKCS #12 file(if above addressed) containing trusted CA certificates used to validate the certificate received from egeria. If this is not specified Mozilla curated defaults are used as provided with node' -- or something like that!. I would keep it at the current default
 * I think I'd change the variable in the code too and just use 'ca' (though can stick with filename)
 
 pfx
--
 * The 'pfx' parm used in this api is documented as 'pfx or pkcs12 encoded private key and certificate chain'
 * This should also be optional - if we're not doing 2 way SSL it's not needed
 * I would document as 'PFX or PKCS12 encoded private key and certificate chain. This is used to specify a certificate to the egeria server when using 2 way SSL' (or similar?). It should contain only the private key and chain required for this connection'
 * The above (ie it must only contain a single file) answers my own question about how to select which key to use
 * Again I'd just update the code to use pfx as the variable for clarity (but with same filename)
 * The current keystore is inappropriate for this use. We really need a cert specifically for the UI. THough the script does create a client cert and thus it's probably reasonable to use that. Will return back when I've sorted #4670
 
 passphrase
 --
 * Document as 'Shared passphrase used to decode the pfx file specified'
 * Also optional (no requirement to be protected)
 
So I think the key observations are
 - corrections to terminology (when the code is done we can update the user doc)
  - the parms are optional
  - I don't think we need more configurability
  - some checking against other sw could be useful

**Comment by planetf1** [comment]
I'm happy to update the code comments / variable names / doc , but as owner perhaps you'd prefer too, and most likely prefer to manage the config aspect?

**Comment by davidradl** [comment]
@planetf1 I will do the code change and have you review - thanks for all your work on this Nigel

**Comment by planetf1** [comment]
Thanks. I'm updating the base code. I'll test and one working will update the hard codesd certs m in to the ui.... pending a longer discussion about how we manage across all our repos

**Comment by davidradl** [comment]
Thanks @planetf1 . I wondering what you think about using new names indicating a later version of the newer truststore, maybe truststorev2rc,p12 then truststorev2.p12 (or a language neutral equivalent). It could be painful if it had the release name in it.

**Comment by planetf1** [comment]
I think we still have a number of issues in our cert management so I'm not particularly feeling we need to do that -- at least yet.

In https://github.com/odpi/egeria/issues/4670 I'm trying to tidy up some of the docs, and more specifically the cert generation process -- and test. We need more clarify over the 'CA' (which is what the truststore is holding), and currently that's called Egeria.p12 (feel free to review that issue). 

For a first-pass I'm proposing to copy over the files into the current places we use them with minimal other changes... but a future step is to look at how we make this process simpler (and secure) across multiple repositories. (and the answer may be purely docs.. and just worry about our demos). I do expect we may move away from any certs checked in, but am hoping this interim step at least offers coherence, and more validation of the techniques typically used to setup the certs..

**Comment by davidradl** [comment]
As a next step, I suggest we expose 5 environment variables - something like :
- egeria-ca 
- egeria-pfx
- egeria-pfx-passphrase
- egeria-browser-cert
- egeria-browser-passphrase.

by default these would point to content in the ssl folder, which would have been copied from Egeria core.
We would update the .envfile sample to include these and the docs to refer to them. 

The values would be overridable for an implementation? For example running in openshift where the certs could have the right hostnames. 

@planetf1 what do you think of this for the UI? Once you have the new server ssl files, I would also need you to create a cert from the ca I can refer to as the API does not seem to accept a p12 file.

**Comment by planetf1** [comment]
@davidradl Also clarify where they are files vs strings -- for example the cert (I know what you propose, just meaning clarification in the docs)
Default sounds good for now - in future we may revisit
Am currently testing replaceability in the base. That's the entry point for an org to include their own certs, including from openshift.. And hit a little snag with some of the certs. working through it. That PR will include not only .p12 files but other formats. Also it is creating p12 files for different components (this is useful for testing) including the UI. But bear in mind you have two interactions ui backend/server and also browser/ui. You need certs for the latter too. Where are they currently? 
In terms of the API, which element doesn't accept p12? It can also sometimes be an issue in terms of what goes into the p12 file. That being said looking around it's clear different tools like different formats, and converting between is entirely normal.

**Comment by davidradl** [comment]
implementing this in #73
