### ISSUE TITLE
Consider should we be removing package-lock.json from git (at least by developer)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#77]
package-lock.json is a generated file that is created when npm install is run, based off resolution of dependencies in package.json

This dependency resolution is a representation of a run on a developers machine, and one purpose is to then allow that code to be moved to another system & have the same level of dependencies present (effectively package.json isn't really respected).

This means that it is subject to the impact of the local environment used by the developer.

In my view in a development environment where we have 'authoritative' build environments, it is there that dependencies should be resolved, just as is the case with maven. It's a neutral arbiter .

Indeed it can result in latent problems being undiscovered whereas in other areas we aim to release rapidly & fail fast.

One may argue that 'definitive' build could usefully save package-lock.json as a build output, in case the combination needs rebuilding in future, or for testing - which after all was the intent of the lock file originally. It may be this isn't necessary with our rapid build/update cycle.  To check it in would then become a build responsibility of course - and it's not something we've done to-date (check in generated files) though I think some of our release process thoughts are starting to expose the fact that this may be a need.

I think this should be considered. My own view is it's the right approach.

 * npm docs https://docs.npmjs.com/cli/v6/configuring-npm/package-locks
 * https://jbeckwith.com/2019/12/18/package-lock/

**Comment by davidradl** [comment]
The first link says "It is highly recommended you commit the generated package lock to source control:". The second link talks of not using the lock file at all. Unless there is a compelling reason, I suggest we stick with the npm docs recommendation, which is the way we have it. Note the lock file was intensionally added to git, as we used not to check it in.

**Comment by davidradl** [comment]
@planetf1 I suggest we can close this

**Comment by planetf1** [comment]
More opinions -> https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi
https://blog.logrocket.com/why-you-should-use-package-lock-json/
https://dev.to/zkat/comment/epbj (from the author)

From these I can see the use case for package-lock.json, but it still seems like a confusion at least for an upstream project.
I do see a reason for incremental dev/deployment, but that seems more relevant to consumers
It's possible the lock file may cause issues with dependabot - though that last link may indicate there is a check for versions being compatible.

Think this needs a little more research/consideration (feel free to assign to me). Not urgent

**Comment by planetf1** [comment]
I think we should close this for now until the point where we have a particular action to take or issues to resolve.
