### ISSUE TITLE
The presentation server not dealing with unexpected errors gracefully. 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#9]
The presentation server is not dealing well with and error (a variable not defined) that causes a  page that we cannot load, which then tries to load index.html from a non existent dist folder. 

 I suspect we should 
1) have a catch all error page instead of pointing to a (non existent folder!) and 
2) think about how we catch these sort of errors in the code so we give a much better experience for the user; catching errors in the frame maybe so we can control what the user sees.

**Comment by grahamwallis** [comment]
The p-s code in Egeria-react-ui needs a general overhaul of things like paths and error handling. I'm working only in that repo now and have run into a number of things that prevent p-s login or fail to handle errors gracefully. I will collate a list at some point of the changes I have made on my local dev branch, and I think we should use this issue to address them.
