### ISSUE TITLE
UI docs and panel - terminology re: server name

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#90]
In the README.md we have references to
 - Egeria React UI server & cra-server
 - Presentation Server
 - view server
 - remoteServerName
 - localServerName

We also have reference to a tenant

Also these, though I think the words stitch the usages together well enough & consistent with the main egeria docs
 - Egeria server
 - metadata server
 - Egeria OMAG Server

In a comment on a PR I asked:

> Is 'serverName' the tenant name (ie coco) rather than the server?

Yes servername is the way we refer to tenants in Egeria. I will merge - if you think it needs more clarification then we can , make further amendments.

_Originally posted by @davidradl in https://github.com/odpi/egeria-react-ui/issues/88#issuecomment-784393425_

I understand this clarification, and it is technically consistent with the use of 'local server name' in the README, but I rather suspect it will be immensely confusing for any users of this UI

I think we need to reevaluate
 - terms like presentation server, local server, remote server, view server
 - ensure we add to a glossary if required (main egeria)?
 - Take care with using 'server name' on the UI -- that is a different user role from that configuring the software. - how will they know this info, what would they likely call it?
 - consider clarifying the environment variable.

I'm ok with the functioning & understand the term usage, but am concerned new users will find this very confusing.

**Comment by davidradl** [comment]
@planetf1 yes that is fair. I think from the discussions yesterday - we need to move most of the readme content into core Egeria documentation; specifically into the admin guide and the development resources. When it is there we should link to the existing definitions of the words, and then add any new terms. Presentation server for me was the capability, but we have used it to refer to the egeria react ui (which we called the Git repo after we had started using the presentation server term). As to what the user would expect here, I am open to suggestions , I suspect we should call it server name or tenant name and have a help link to define exactly what it means. We expect users will usually be given the tenanted url, this screen is likely to be shown for a developer running in developer mode (as you did); hopefully this screen makes the experience a bit better than it was. Open to suggestions on the wordings.
